### ISSUE TITLE
New version Portainer 2.0

### ISSUE THREAD

**Issue by ghost** [evertramos/docker-portainer-letsencrypt#8]
Hi Evert,

There is a new release of Portainer (Release 2.0.0) https://github.com/portainer/portainer/releases/tag/2.0.0

But with your repository, I have a old version : 1.24.1

Is it possible to update your repository.

Thank a lot

Have a nice day

Christophe

**Comment by HomeServerPro** [comment]
Just change line in `doccker-compose.yml`
`image: portainer/portainer-ce
`

**Comment by ghost** [comment]
Hi,
Thank for your reply, but is not good. Are you sure ?

```
version: '3'

services:
  portainer:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    image: portainer/portainer-ce
    volumes:
      - ${PORTAINER_DATA_PATH}:/data
      - ${PORTAINER_SSL_PATH}:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      SSL:
      SSLCERT: ${PORTAINER_SSL_CERTIFICATE}
      SSLKEY: ${PORTAINER_SSL_KEY}

networks:
    default:
       external:
         name: ${NETWORK}
```

**Comment by HomeServerPro** [comment]
> Hi,
> Thank for your reply, but is not good. Are you sure ?

Sorry, my mistake...
Realy working `.yml`:

```
version: '3'

services:
  portainer:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    image: portainer/portainer-ce
    volumes:
      - ./${CONTAINER_NAME}:/data
      - ${PORTAINER_SSL_PATH}:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
      - "8000:8000"
    expose:
      - "9000"
      - "8000"
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: ${DOMAINS}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      SSL:
      SSLCERT: ${PORTAINER_SSL_CERTIFICATE}
      SSLKEY: ${PORTAINER_SSL_KEY}

networks:
    default:
       external:
         name: ${NETWORK}
```
